CREATE TABLE receipts (
  id INT UNSIGNED AUTO_INCREMENT,
  merchant VARCHAR(255),
  amount DECIMAL(12,2),
  receipt_type INT UNSIGNED,

  PRIMARY KEY (id)
);

CREATE TABLE tags (
  iid INT UNSIGNED AUTO_INCREMENT,
  id INT UNSIGNED,
  tag VARCHAR(255),
  PRIMARY KEY (iid)
);